# Generated by Django 4.2 on 2024-03-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='back_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
