# Generated by Django 4.2 on 2024-03-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_back_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='detail_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
