# Generated by Django 5.0.4 on 2024-04-08 09:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
